---
name: Check inputs for cron and dispatch
on:
  workflow_dispatch:

jobs:
  test-job:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test exit codes
        shell: bash
        run: echo -e "v0.12.0\n0.11.3" | sort -V -C


