---
name: Check inputs for cron and dispatch
on:
  schedule:
  # Every 10 minutes
  - cron: "*/5 * * * *"
  #workflow_dispatch:
  #  inputs:
  #    delete-all-keypairs:
  #      type: boolean
  #      description: "Delete all CI user keypairs"
  #      required: true
  #    delete-resources:
  #      type: boolean
  #      description: "Delete resources older than 6h"
  #      required: true

jobs:
  ci-cleanup:
    strategy:
      matrix:
        target-cloud: [arcus, leafcloud]
    name: Check inputs
    runs-on: ubuntu-latest
    steps:
      - name: Check inputs
        run: |
          echo "INPUT (delete-all-keypairs): ${{ inputs.delete-all-keypairs }}"
          echo "INPUT (delete-resources): ${{ inputs.delete-resources }}"

